packages:
  - apps/*
  - packages/*
  - products/*
allowBuilds:
  esbuild: false
  sharp: false
  tldjs: false

catalog:
  "@types/react": ^19.2.14
  "@types/react-dom": ^19.2.3
  "@types/node": ^22.19.0
  react: ^19.2.4
  react-dom: ^19.2.4
  tsx: ^4.21.0
  typescript: ^5.9.3
  vitest: ^4.1.2
  zod: ^4.3.6
