// Generated by drizzle-kit pull --init. Do not edit by hand.
import { sql } from "drizzle-orm";
import {
  pgSchema,
  text,
  timestamp,
  bigint,
  boolean,
  integer,
  jsonb,
  index,
  foreignKey,
  primaryKey,
  check,
  pgPolicy,
} from "drizzle-orm/pg-core";

export const interview = pgSchema("interview");

export const assistantAnswerRevisions = interview.table.withRLS(
  "assistant_answer_revisions",
  {
    tenantId: text("tenant_id").notNull(),
    actorId: text("actor_id").notNull(),
    productId: text("product_id").notNull(),
    workspaceId: text("workspace_id").notNull(),
    artifactId: text("artifact_id").notNull(),
    savedRevision: bigint("saved_revision", { mode: "number" }).notNull(),
    draftRevision: bigint("draft_revision", { mode: "number" }).notNull(),
    value: jsonb().notNull(),
    createdAt: timestamp("created_at", { withTimezone: true })
      .default(sql`now()`)
      .notNull(),
    provenance: jsonb(),
  },
  (table) => [
    primaryKey({
      columns: [
        table.tenantId,
        table.actorId,
        table.productId,
        table.workspaceId,
        table.artifactId,
        table.savedRevision,
      ],
      name: "assistant_answer_revisions_pkey",
    }),
    foreignKey({
      columns: [
        table.tenantId,
        table.actorId,
        table.productId,
        table.workspaceId,
        table.artifactId,
      ],
      foreignColumns: [
        assistantDrafts.tenantId,
        assistantDrafts.actorId,
        assistantDrafts.productId,
        assistantDrafts.workspaceId,
        assistantDrafts.artifactId,
      ],
      name: "assistant_answer_revisions_tenant_id_actor_id_product_id_w_fkey",
    }),

    pgPolicy("assistant_private_scope", {
      using: sql`((tenant_id = current_setting('app.tenant_id'::text, true)) AND (actor_id = current_setting('app.actor_id'::text, true)) AND (product_id = current_setting('app.product_id'::text, true)))`,
      withCheck: sql`((tenant_id = current_setting('app.tenant_id'::text, true)) AND (actor_id = current_setting('app.actor_id'::text, true)) AND (product_id = current_setting('app.product_id'::text, true)))`,
    }),
    check(
      "assistant_answer_revisions_draft_revision_check",
      sql`(draft_revision >= 0)`,
    ),
    check(
      "assistant_answer_revisions_saved_revision_check",
      sql`(saved_revision > 0)`,
    ),
  ],
);

export const assistantDrafts = interview.table.withRLS(
  "assistant_drafts",
  {
    tenantId: text("tenant_id").notNull(),
    actorId: text("actor_id").notNull(),
    productId: text("product_id").notNull(),
    workspaceId: text("workspace_id").notNull(),
    artifactId: text("artifact_id").notNull(),
    revision: bigint({ mode: "number" }).default(0).notNull(),
    savedRevision: bigint("saved_revision", { mode: "number" })
      .default(0)
      .notNull(),
    value: jsonb().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .default(sql`now()`)
      .notNull(),
    provenance: jsonb(),
  },
  (table) => [
    primaryKey({
      columns: [
        table.tenantId,
        table.actorId,
        table.productId,
        table.workspaceId,
        table.artifactId,
      ],
      name: "assistant_drafts_pkey",
    }),

    pgPolicy("assistant_private_scope", {
      using: sql`((tenant_id = current_setting('app.tenant_id'::text, true)) AND (actor_id = current_setting('app.actor_id'::text, true)) AND (product_id = current_setting('app.product_id'::text, true)))`,
      withCheck: sql`((tenant_id = current_setting('app.tenant_id'::text, true)) AND (actor_id = current_setting('app.actor_id'::text, true)) AND (product_id = current_setting('app.product_id'::text, true)))`,
    }),
    check("assistant_drafts_revision_check", sql`(revision >= 0)`),
  ],
);

export const assistantEffectReceipts = interview.table.withRLS(
  "assistant_effect_receipts",
  {
    tenantId: text("tenant_id").notNull(),
    actorId: text("actor_id").notNull(),
    productId: text("product_id").notNull(),
    operation: text().notNull(),
    requestId: text("request_id").notNull(),
    id: text().notNull(),
    fingerprint: text().notNull(),
    payload: jsonb().notNull(),
    state: text().notNull(),
    result: jsonb(),
    createdAt: timestamp("created_at", { withTimezone: true })
      .default(sql`now()`)
      .notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .default(sql`now()`)
      .notNull(),
  },
  (table) => [
    primaryKey({
      columns: [
        table.tenantId,
        table.actorId,
        table.productId,
        table.operation,
        table.requestId,
      ],
      name: "assistant_effect_receipts_pkey",
    }),

    pgPolicy("assistant_private_scope", {
      using: sql`((tenant_id = current_setting('app.tenant_id'::text, true)) AND (actor_id = current_setting('app.actor_id'::text, true)) AND (product_id = current_setting('app.product_id'::text, true)))`,
      withCheck: sql`((tenant_id = current_setting('app.tenant_id'::text, true)) AND (actor_id = current_setting('app.actor_id'::text, true)) AND (product_id = current_setting('app.product_id'::text, true)))`,
    }),
    check(
      "assistant_effect_receipts_check",
      sql`(((state = 'completed'::text) AND (result IS NOT NULL)) OR ((state <> 'completed'::text) AND (result IS NULL)))`,
    ),
    check(
      "assistant_effect_receipts_fingerprint_check",
      sql`(fingerprint ~ '^[a-f0-9]{64}$'::text)`,
    ),
    check(
      "assistant_effect_receipts_operation_check",
      sql`(operation = ANY (ARRAY['save'::text, 'run-code'::text]))`,
    ),
    check(
      "assistant_effect_receipts_state_check",
      sql`(state = ANY (ARRAY['started'::text, 'completed'::text, 'interrupted'::text]))`,
    ),
  ],
);

export const assistantEvidence = interview.table.withRLS(
  "assistant_evidence",
  {
    tenantId: text("tenant_id").notNull(),
    actorId: text("actor_id").notNull(),
    productId: text("product_id").notNull(),
    id: text().notNull(),
    revision: bigint({ mode: "number" }).notNull(),
    sha256: text().notNull(),
    locator: text().notNull(),
    text: text().notNull(),
    sourceKind: text("source_kind").notNull(),
    classification: text().notNull(),
    audience: text().array().notNull(),
    metrics: jsonb().default([]).notNull(),
  },
  (table) => [
    primaryKey({
      columns: [
        table.tenantId,
        table.actorId,
        table.productId,
        table.id,
        table.revision,
      ],
      name: "assistant_evidence_pkey",
    }),
    index("assistant_evidence_search").using(
      "gin",
      sql`to_tsvector('english'::regconfig, text)`,
    ),

    pgPolicy("assistant_private_scope", {
      using: sql`((tenant_id = current_setting('app.tenant_id'::text, true)) AND (actor_id = current_setting('app.actor_id'::text, true)) AND (product_id = current_setting('app.product_id'::text, true)))`,
      withCheck: sql`((tenant_id = current_setting('app.tenant_id'::text, true)) AND (actor_id = current_setting('app.actor_id'::text, true)) AND (product_id = current_setting('app.product_id'::text, true)))`,
    }),
    check(
      "assistant_evidence_audience_check",
      sql`(cardinality(audience) > 0)`,
    ),
    check(
      "assistant_evidence_classification_check",
      sql`(classification = ANY (ARRAY['public'::text, 'internal'::text, 'confidential'::text, 'restricted'::text]))`,
    ),
    check("assistant_evidence_revision_check", sql`(revision >= 0)`),
    check(
      "assistant_evidence_sha256_check",
      sql`(sha256 ~ '^[a-f0-9]{64}$'::text)`,
    ),
    check(
      "assistant_evidence_source_kind_check",
      sql`(source_kind = ANY (ARRAY['candidate'::text, 'technical-reference'::text]))`,
    ),
  ],
);

export const assistantReverts = interview.table.withRLS(
  "assistant_reverts",
  {
    tenantId: text("tenant_id").notNull(),
    actorId: text("actor_id").notNull(),
    productId: text("product_id").notNull(),
    proposalId: text("proposal_id").notNull(),
    workspaceId: text("workspace_id").notNull(),
    artifactId: text("artifact_id").notNull(),
    appliedRevision: bigint("applied_revision", { mode: "number" }).notNull(),
    previousValue: jsonb("previous_value").notNull(),
    previousProvenance: jsonb("previous_provenance"),
    revertedRevision: bigint("reverted_revision", { mode: "number" }),
    createdAt: timestamp("created_at", { withTimezone: true })
      .default(sql`now()`)
      .notNull(),
  },
  (table) => [
    primaryKey({
      columns: [
        table.tenantId,
        table.actorId,
        table.productId,
        table.proposalId,
      ],
      name: "assistant_reverts_pkey",
    }),
    foreignKey({
      columns: [
        table.tenantId,
        table.actorId,
        table.productId,
        table.workspaceId,
        table.artifactId,
      ],
      foreignColumns: [
        assistantDrafts.tenantId,
        assistantDrafts.actorId,
        assistantDrafts.productId,
        assistantDrafts.workspaceId,
        assistantDrafts.artifactId,
      ],
      name: "assistant_reverts_tenant_id_actor_id_product_id_workspace__fkey",
    }),

    pgPolicy("assistant_private_scope", {
      using: sql`((tenant_id = current_setting('app.tenant_id'::text, true)) AND (actor_id = current_setting('app.actor_id'::text, true)) AND (product_id = current_setting('app.product_id'::text, true)))`,
      withCheck: sql`((tenant_id = current_setting('app.tenant_id'::text, true)) AND (actor_id = current_setting('app.actor_id'::text, true)) AND (product_id = current_setting('app.product_id'::text, true)))`,
    }),
    check(
      "assistant_reverts_applied_revision_check",
      sql`(applied_revision >= 0)`,
    ),
    check(
      "assistant_reverts_reverted_revision_check",
      sql`(reverted_revision >= 0)`,
    ),
  ],
);

export const briefingProposals = interview.table.withRLS(
  "briefing_proposals",
  {
    tenantId: text("tenant_id").notNull(),
    actorId: text("actor_id").notNull(),
    productId: text("product_id").notNull(),
    id: text().notNull(),
    artifactId: text("artifact_id").notNull(),
    baseRevision: bigint("base_revision", { mode: "number" }).notNull(),
    profileId: text("profile_id").notNull(),
    profileRevision: bigint("profile_revision", { mode: "number" }).notNull(),
    profileSha256: text("profile_sha256").notNull(),
    value: jsonb().notNull(),
    sourceSnapshot: jsonb("source_snapshot").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true })
      .default(sql`now()`)
      .notNull(),
  },
  (table) => [
    primaryKey({
      columns: [table.tenantId, table.actorId, table.productId, table.id],
      name: "briefing_proposals_pkey",
    }),

    pgPolicy("briefing_private_scope", {
      using: sql`((tenant_id = current_setting('app.tenant_id'::text, true)) AND (actor_id = current_setting('app.actor_id'::text, true)) AND (product_id = current_setting('app.product_id'::text, true)))`,
      withCheck: sql`((tenant_id = current_setting('app.tenant_id'::text, true)) AND (actor_id = current_setting('app.actor_id'::text, true)) AND (product_id = current_setting('app.product_id'::text, true)))`,
    }),
    check("briefing_proposals_base_revision_check", sql`(base_revision >= 0)`),
  ],
);

export const candidateProfileRevisions = interview.table.withRLS(
  "candidate_profile_revisions",
  {
    tenantId: text("tenant_id").notNull(),
    actorId: text("actor_id").notNull(),
    productId: text("product_id").notNull(),
    id: text().notNull(),
    revision: bigint({ mode: "number" }).notNull(),
    name: text().notNull(),
    sha256: text().notNull(),
    matrix: jsonb().notNull(),
    createdAt: timestamp("created_at", { withTimezone: true })
      .default(sql`now()`)
      .notNull(),
  },
  (table) => [
    primaryKey({
      columns: [
        table.tenantId,
        table.actorId,
        table.productId,
        table.id,
        table.revision,
      ],
      name: "candidate_profile_revisions_pkey",
    }),
    foreignKey({
      columns: [table.tenantId, table.actorId, table.productId, table.id],
      foreignColumns: [
        candidateProfiles.tenantId,
        candidateProfiles.actorId,
        candidateProfiles.productId,
        candidateProfiles.id,
      ],
      name: "candidate_profile_revisions_tenant_id_actor_id_product_id__fkey",
    }),

    pgPolicy("briefing_private_scope", {
      using: sql`((tenant_id = current_setting('app.tenant_id'::text, true)) AND (actor_id = current_setting('app.actor_id'::text, true)) AND (product_id = current_setting('app.product_id'::text, true)))`,
      withCheck: sql`((tenant_id = current_setting('app.tenant_id'::text, true)) AND (actor_id = current_setting('app.actor_id'::text, true)) AND (product_id = current_setting('app.product_id'::text, true)))`,
    }),
    check("candidate_profile_revisions_revision_check", sql`(revision >= 1)`),
    check(
      "candidate_profile_revisions_sha256_check",
      sql`(sha256 ~ '^[a-f0-9]{64}$'::text)`,
    ),
  ],
);

export const candidateProfiles = interview.table.withRLS(
  "candidate_profiles",
  {
    tenantId: text("tenant_id").notNull(),
    actorId: text("actor_id").notNull(),
    productId: text("product_id").notNull(),
    id: text().notNull(),
    name: text().notNull(),
    revision: bigint({ mode: "number" }).notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .default(sql`now()`)
      .notNull(),
    revokedAt: timestamp("revoked_at", { withTimezone: true }),
  },
  (table) => [
    primaryKey({
      columns: [table.tenantId, table.actorId, table.productId, table.id],
      name: "candidate_profiles_pkey",
    }),

    pgPolicy("briefing_private_scope", {
      using: sql`((tenant_id = current_setting('app.tenant_id'::text, true)) AND (actor_id = current_setting('app.actor_id'::text, true)) AND (product_id = current_setting('app.product_id'::text, true)))`,
      withCheck: sql`((tenant_id = current_setting('app.tenant_id'::text, true)) AND (actor_id = current_setting('app.actor_id'::text, true)) AND (product_id = current_setting('app.product_id'::text, true)))`,
    }),
    check("candidate_profiles_revision_check", sql`(revision >= 1)`),
  ],
);

export const conceptBriefs = interview.table.withRLS(
  "concept_briefs",
  {
    tenantId: text("tenant_id").notNull(),
    actorId: text("actor_id").notNull(),
    productId: text("product_id").notNull(),
    id: text().notNull(),
    kind: text().notNull(),
    topic: text().notNull(),
    value: jsonb().notNull(),
    createdAt: timestamp("created_at", { withTimezone: true })
      .default(sql`now()`)
      .notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .default(sql`now()`)
      .notNull(),
  },
  (table) => [
    primaryKey({
      columns: [table.tenantId, table.actorId, table.productId, table.id],
      name: "concept_briefs_pkey",
    }),

    pgPolicy("brief_private_scope", {
      using: sql`((tenant_id = current_setting('app.tenant_id'::text, true)) AND (actor_id = current_setting('app.actor_id'::text, true)) AND (product_id = current_setting('app.product_id'::text, true)))`,
      withCheck: sql`((tenant_id = current_setting('app.tenant_id'::text, true)) AND (actor_id = current_setting('app.actor_id'::text, true)) AND (product_id = current_setting('app.product_id'::text, true)))`,
    }),
    check(
      "concept_briefs_kind_check",
      sql`(kind = ANY (ARRAY['concept'::text, 'system-design'::text]))`,
    ),
  ],
);

export const interviewPlanItems = interview.table.withRLS(
  "interview_plan_items",
  {
    tenantId: text("tenant_id").notNull(),
    actorId: text("actor_id").notNull(),
    productId: text("product_id").notNull(),
    id: text().notNull(),
    planId: text("plan_id").notNull(),
    kind: text().notNull(),
    ref: text(),
    title: text().notNull(),
    done: boolean().default(false).notNull(),
    position: integer().default(0).notNull(),
    createdAt: timestamp("created_at", { withTimezone: true })
      .default(sql`now()`)
      .notNull(),
  },
  (table) => [
    primaryKey({
      columns: [table.tenantId, table.actorId, table.productId, table.id],
      name: "interview_plan_items_pkey",
    }),
    foreignKey({
      columns: [table.tenantId, table.actorId, table.productId, table.planId],
      foreignColumns: [
        interviewPlans.tenantId,
        interviewPlans.actorId,
        interviewPlans.productId,
        interviewPlans.id,
      ],
      name: "interview_plan_items_tenant_id_actor_id_product_id_plan_id_fkey",
    }).onDelete("cascade"),

    pgPolicy("plan_private_scope", {
      using: sql`((tenant_id = current_setting('app.tenant_id'::text, true)) AND (actor_id = current_setting('app.actor_id'::text, true)) AND (product_id = current_setting('app.product_id'::text, true)))`,
      withCheck: sql`((tenant_id = current_setting('app.tenant_id'::text, true)) AND (actor_id = current_setting('app.actor_id'::text, true)) AND (product_id = current_setting('app.product_id'::text, true)))`,
    }),
    check(
      "interview_plan_items_kind_check",
      sql`(kind = ANY (ARRAY['question'::text, 'briefing'::text, 'rehearsal'::text, 'task'::text]))`,
    ),
  ],
);

export const interviewPlans = interview.table.withRLS(
  "interview_plans",
  {
    tenantId: text("tenant_id").notNull(),
    actorId: text("actor_id").notNull(),
    productId: text("product_id").notNull(),
    id: text().notNull(),
    company: text().notNull(),
    role: text().notNull(),
    scheduledAt: timestamp("scheduled_at", { withTimezone: true }),
    durationMinutes: integer("duration_minutes"),
    format: text().default("").notNull(),
    topics: jsonb().default([]).notNull(),
    createdAt: timestamp("created_at", { withTimezone: true })
      .default(sql`now()`)
      .notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .default(sql`now()`)
      .notNull(),
  },
  (table) => [
    primaryKey({
      columns: [table.tenantId, table.actorId, table.productId, table.id],
      name: "interview_plans_pkey",
    }),

    pgPolicy("plan_private_scope", {
      using: sql`((tenant_id = current_setting('app.tenant_id'::text, true)) AND (actor_id = current_setting('app.actor_id'::text, true)) AND (product_id = current_setting('app.product_id'::text, true)))`,
      withCheck: sql`((tenant_id = current_setting('app.tenant_id'::text, true)) AND (actor_id = current_setting('app.actor_id'::text, true)) AND (product_id = current_setting('app.product_id'::text, true)))`,
    }),
    check(
      "interview_plans_duration_minutes_check",
      sql`((duration_minutes >= 5) AND (duration_minutes <= 600))`,
    ),
  ],
);

export const rehearsalSessions = interview.table.withRLS(
  "rehearsal_sessions",
  {
    tenantId: text("tenant_id").notNull(),
    actorId: text("actor_id").notNull(),
    productId: text("product_id").notNull(),
    id: text().notNull(),
    format: text().notNull(),
    score: integer().notNull(),
    value: jsonb().notNull(),
    endedAt: timestamp("ended_at", { withTimezone: true }).notNull(),
    createdAt: timestamp("created_at", { withTimezone: true })
      .default(sql`now()`)
      .notNull(),
  },
  (table) => [
    primaryKey({
      columns: [table.tenantId, table.actorId, table.productId, table.id],
      name: "rehearsal_sessions_pkey",
    }),

    pgPolicy("rehearsal_private_scope", {
      using: sql`((tenant_id = current_setting('app.tenant_id'::text, true)) AND (actor_id = current_setting('app.actor_id'::text, true)) AND (product_id = current_setting('app.product_id'::text, true)))`,
      withCheck: sql`((tenant_id = current_setting('app.tenant_id'::text, true)) AND (actor_id = current_setting('app.actor_id'::text, true)) AND (product_id = current_setting('app.product_id'::text, true)))`,
    }),
    check(
      "rehearsal_sessions_format_check",
      sql`(format = ANY (ARRAY['full'::text, 'coding'::text, 'concept'::text]))`,
    ),
    check(
      "rehearsal_sessions_score_check",
      sql`((score >= 0) AND (score <= 100))`,
    ),
  ],
);
