// The claims inventory: every interactive control of the live session, on the
// web page and in the native panel, with WHAT ITS LABEL OR TOOLTIP SAYS IT DOES
// and what REAL effect proves that. The rule of this suite: a control is covered
// only by a spec that observes the effect named here (a server row, an HTTP
// result, a recorded native bridge call, clipboard contents, a DOM change only
// the real behaviour can produce), never by the control merely being present.
//
// `claims-coverage.spec.ts` scans the rendered pages and FAILS on a control that
// is not matched below, and on a `covered` entry whose spec title does not exist.
// `pending` entries are the worklist: they fail the run only with E2E_STRICT=1.
// To cover one: write the spec, set `status: "covered"` and `spec` to a
// substring of its title.
export type Surface = "web" | "native";

export type EffectKind =
  | "server" // a row or HTTP result the server holds
  | "bridge" // a recorded native host call (window.studioHost)
  | "clipboard" // navigator.clipboard contents
  | "dom" // a state change only the real behaviour can produce
  | "navigation"; // the URL or window the control leads to

export type Claim = {
  id: string;
  surface: Surface;
  // The part of the page that owns the control.
  where: string;
  role: string;
  // Matched against the accessible name: exact string, or a pattern for names
  // that carry times, ordinals or state.
  name: string | RegExp;
  // What the label, tooltip or surrounding copy says the control does.
  claim: string;
  effect: { kind: EffectKind; detail: string };
  status: "covered" | "pending";
  // A substring of the title of the spec that asserts the effect.
  spec?: string;
};

type Row = [
  id: string,
  where: string,
  role: string,
  name: string | RegExp,
  claim: string,
  kind: EffectKind,
  detail: string,
  spec?: string,
];

const make = (surface: Surface, rows: Row[]): Claim[] =>
  rows.map(([id, where, role, name, claim, kind, detail, spec]) => ({
    id,
    surface,
    where,
    role,
    name,
    claim,
    effect: { kind, detail },
    status: spec ? "covered" : "pending",
    ...(spec ? { spec } : {}),
  }));

const SMOKE_START = "web smoke: sign in, start a rehearsal";
const SMOKE_END = "web smoke: End with confirmation";
const SMOKE_SIGNIN = "web smoke: unauthenticated";
const SMOKE_NATIVE = "native smoke: panel toolbar";

// The Screenshots icon, strip, Manual tray and viewer (D28-D31, T17b): one set
// of rows for both surfaces (the controls and their words are the same).
// Covered through COVERED_BY below; a row not named there is still pending.
const screenshotRows = (surface: Surface): Row[] => [
  [
    `${surface}.screenshots.toggle`,
    "task",
    "button",
    /^Screenshots \(\d+\)$/,
    "Shows or hides this task's screenshots; the badge counts stored plus staged",
    "dom",
    "aria-expanded flips and the area appears under the task line; the count equals the server's list for the task plus the staged ones",
  ],
  [
    `${surface}.screenshots.thumb`,
    "task",
    "button",
    /^Open (S\d+|New \d+)$/,
    "Opens that screenshot in the viewer",
    "dom",
    "a dialog opens with the S-label, time, display label and text state; a stored image loads only from /sessions/:id/screenshots/:artifact",
  ],
  [
    `${surface}.screenshots.scroll`,
    "task",
    "button",
    /^Scroll screenshots (left|right)$/,
    "Scrolls the strip of thumbnails sideways",
    "dom",
    "the strip's scrollLeft changes when there are more thumbnails than fit",
  ],
  [
    `${surface}.screenshots.add`,
    "task",
    "button",
    "Add screenshot",
    "Captures the screen and stages it on this device; nothing is sent",
    "server",
    "the staged item says Not sent yet and the server holds NO new capture until Apply; disabled with the device-only reason before anything is added",
  ],
  [
    `${surface}.screenshots.intent`,
    "task",
    "radio",
    /^(New problem|Add to T\d+)$/,
    "Chooses whether Apply starts a new task or revises this one",
    "server",
    "Apply after New problem posts a capture with no target; after Add to T{n} posts it with that task and revision",
  ],
  [
    `${surface}.screenshots.apply`,
    "task",
    "button",
    /^(Apply|Retry)$/,
    "Sends every staged screenshot, in order, with its text, as one request",
    "server",
    "exactly one capture (or one regenerate with nothing staged) reaches the server; the task gains one revision (or a new task appears) and the previous answer is marked Outdated; Retry reuses the request id",
  ],
  [
    `${surface}.screenshots.discard`,
    "task",
    "button",
    "Discard",
    "Drops the staged screenshots without sending them",
    "server",
    "the tray empties and the server holds no new capture",
  ],
  [
    `${surface}.screenshots.crop`,
    "task",
    "button",
    /^Crop (New \d+)$/,
    "Opens the crop editor for that staged screenshot",
    "dom",
    "applying a crop replaces the staged bytes with a smaller image (at least 32 px a side) and the text is read again; the uploaded image has the cropped size",
  ],
  [
    `${surface}.screenshots.move`,
    "task",
    "button",
    /^Move (New \d+) (left|right)$/,
    "Moves that staged screenshot one place",
    "server",
    "the order of the images in the one capture request follows the tray",
  ],
  [
    `${surface}.screenshots.remove`,
    "task",
    "button",
    /^Remove (New \d+)$/,
    "Removes that staged screenshot",
    "dom",
    "the item leaves the tray and its object URL is revoked; it is not in the request",
  ],
  [
    `${surface}.screenshots.viewer-zoom`,
    "task",
    "button",
    /^(Zoom in|Zoom out|Fit|100%)$/,
    "Zooms the screenshot in the viewer",
    "dom",
    "the zoom readout changes (Fit, 150%, 100% ...) and the image is drawn at that scale",
  ],
  [
    `${surface}.screenshots.viewer-close`,
    "task",
    "button",
    "Close viewer",
    "Closes the viewer and returns to the thumbnail",
    "dom",
    "the dialog is gone and focus is back on the thumbnail that opened it",
  ],
  [
    `${surface}.screenshots.viewer-crop`,
    "task",
    "button",
    /^(Crop|Apply crop|Reset|Cancel)$/,
    "Crops the staged screenshot to the selection",
    "dom",
    "Apply crop closes the viewer and the tray item is the cropped image; Reset restores the whole image; Cancel leaves it as it was",
  ],
  [
    `${surface}.screenshots.crop-handle`,
    "task",
    "button",
    /^Crop edge: /,
    "Resizes the crop selection from that edge (arrow keys nudge it)",
    "dom",
    "the Output W x H readout changes and never goes below 32 px a side",
  ],
  [
    `${surface}.screenshots.crop-field`,
    "task",
    "spinbutton",
    /^(Left|Top|Width|Height)$/,
    "Sets that side of the crop in image pixels",
    "dom",
    "the Output W x H readout follows the typed numbers, clamped to the image",
  ],
  // ---- Screenshots to the model (D35, T22b) -----------------------------------
  [
    `${surface}.screenshots.send-setting`,
    surface === "web" ? "sources" : "settings",
    "radio",
    /^(Always send|Text only when the screen is just text|Never send images)/,
    "Chooses what of each screenshot goes to the model: image and text, text only when the screen is just text, or text only always",
    "server",
    "one POST .../screenshot-send with that value, the saved value shown from the session record, and the next scripted model call carries the matching image count; disabled with a reason when the session is device-only or ended",
    surface === "web"
      ? "web Sources tab: each radio posts once"
      : "native Settings window (Privacy)",
  ],
  [
    `${surface}.screenshots.sent-as`,
    "task",
    "button",
    /^Open S\d+$/,
    "Each stored screenshot says whether its image or only its text was sent (Image sent, Sent as text only, Not sent) and nothing when the server recorded nothing",
    "dom",
    "the label equals the server's sentByRevision for the screenshot (newest revision), and the viewer header lists every revision's outcome",
    surface === "web"
      ? "web Screenshots to the model, "
      : "native Screenshots viewer: Open S1",
  ],
  [
    `${surface}.screenshots.setting-tooltip`,
    "task",
    "button",
    /^Screenshots \(\d+\)$/,
    "The screenshots button's tooltip names the active setting (Screenshots to the model: Always, Text only when text, Never)",
    "dom",
    "the title attribute follows the saved setting after a change in Settings",
    surface === "web"
      ? "web Screenshots to the model, "
      : "native Settings window (Privacy)",
  ],
];

// The capture problem banner (T32, plan 7.0o): why a capture or analysis did not
// run, what to do, and a button where the app can help. One set of rows for both
// surfaces. Covered: the dismiss on both surfaces and open-settings on native (see COVERED_BY).
// PENDING web.capture-problem.open-settings: the button shows only when a native shell reports permission-denied; a plain web page has no host shim, so the web level cannot raise it (native covers the same control).
const captureProblemRows = (surface: Surface): Row[] => [
  [
    `${surface}.capture-problem.dismiss`,
    surface === "web" ? "live page" : "answer pane",
    "button",
    "Dismiss message",
    "Dismisses the capture problem banner",
    "dom",
    "the banner (data-testid capture-problem) is removed and stays removed until another capture fails",
  ],
  [
    `${surface}.capture-problem.open-settings`,
    surface === "web" ? "live page" : "answer pane",
    "button",
    "Open Screen Recording settings",
    "Opens the macOS Screen Recording privacy pane so the app can be allowed",
    "bridge",
    "the host shim records one openExternal call with exactly x-apple.systempreferences:com.apple.preference.security?Privacy_ScreenCapture; shown only when the shell reports permission-denied",
  ],
];

export const WEB_CLAIMS: Claim[] = make("web", [
  ...screenshotRows("web"),
  ...captureProblemRows("web"),
  // ---- Studio shell around the live page --------------------------------
  [
    "web.shell.nav-home",
    "shell",
    "button",
    /^Home\b/,
    "Opens Home",
    "navigation",
    "URL/view changes to the home view",
  ],
  [
    "web.shell.nav-workspace",
    "shell",
    "button",
    /^Workspace\b/,
    "Opens Workspace",
    "navigation",
    "URL/view changes to workspace",
  ],
  [
    "web.shell.nav-briefings",
    "shell",
    "button",
    /^Briefings\b/,
    "Opens Briefings",
    "navigation",
    "URL/view changes to briefings",
  ],
  [
    "web.shell.nav-documents",
    "shell",
    "button",
    /^Documents\b/,
    "Opens Documents",
    "navigation",
    "URL/view changes to documents",
  ],
  [
    "web.shell.nav-knowledge",
    "shell",
    "button",
    /^Knowledge\b/,
    "Opens Knowledge",
    "navigation",
    "URL/view changes to knowledge",
  ],
  [
    "web.shell.nav-rehearsal",
    "shell",
    "button",
    /^Rehearsal\b/,
    "Opens Rehearsal",
    "navigation",
    "URL/view changes to rehearsal",
  ],
  [
    "web.shell.nav-live",
    "shell",
    "button",
    /^Live session\b/,
    "Opens Live session; shows a 'Session in progress' dot only while the server's session is open",
    "dom",
    "dot present iff a session row is active/paused (read the DB, then the dot)",
  ],
  [
    "web.shell.search",
    "shell",
    "button",
    /^Search or jump to/,
    "Opens the command palette (Cmd+K)",
    "dom",
    "a dialog with a search field opens; choosing 'Live session' navigates",
  ],
  [
    "web.shell.theme",
    "shell",
    "button",
    /^Use (dark|light) theme$/,
    "Switches the theme",
    "dom",
    "document dataset theme flips and persists across reload",
  ],
  [
    "web.shell.assistant",
    "shell",
    "button",
    "Assistant",
    "Opens the Studio assistant",
    "dom",
    "assistant panel opens",
  ],
  [
    "web.shell.presentations",
    "shell",
    "link",
    "Presentations",
    "Opens the Presentations product",
    "navigation",
    "URL becomes /t/local/p/presentation",
  ],

  // ---- Sign-in page ---------------------------------------------------------
  [
    "web.signin.local",
    "sign-in",
    "button",
    "Continue as local user",
    "Signs in as the local development user and lands on the workspace",
    "navigation",
    "a session cookie is set and /t/local loads signed in",
    SMOKE_SIGNIN,
  ],
  // PENDING: needs the Google OAuth provider configured (real client credentials); the harness stack has none, and web sign-in is being reworked by the WEB package.
  [
    "web.signin.google",
    "sign-in",
    "button",
    "Continue with Google",
    "Starts Google sign-in",
    "navigation",
    "redirects to the Google authorize URL (provider not reachable in the harness: assert the redirect target only)",
  ],
  // PENDING: needs the LinkedIn OAuth provider configured (real client credentials); see web.signin.google.
  [
    "web.signin.linkedin",
    "sign-in",
    "button",
    "Continue with LinkedIn",
    "Starts LinkedIn sign-in",
    "navigation",
    "redirects to the LinkedIn authorize URL (assert the redirect target only)",
  ],

  // ---- Setup page ----------------------------------------------------------
  [
    "web.setup.target-rehearsal",
    "setup",
    "radio",
    /^Rehearsal Practice with no interview/,
    "Starts a rehearsal with no interview attached",
    "server",
    "started session row has rehearsal_run_id set",
    SMOKE_START,
  ],
  [
    "web.setup.screenshot-send",
    "setup",
    "radio",
    /^(Always send|Text only when the screen is just text|Never send images)/,
    "Chooses, before the session starts, what of each screenshot goes to the model",
    "server",
    "the start request carries screenshotSend when it is not the default, and the started session record holds it; disabled with the device-only reason when Device only is chosen",
    "web setup: the Screenshots to the model row starts on Always",
  ],
  [
    "web.setup.consent",
    "setup",
    "checkbox",
    /^Everyone in this interview has agreed/,
    "Required to start; Studio does not store the answer",
    "server",
    "Start stays disabled with its reason until checked; no consent column or key exists in the session row",
    "setup consent:",
  ],
  [
    "web.setup.strict",
    "setup",
    "checkbox",
    /^Strict rehearsal/,
    "Live assistance stays off, like the real thing",
    "server",
    "session row strict=true and no model call is ever made",
    "setup strict rehearsal",
  ],
  [
    "web.setup.host-mac",
    "setup",
    "radio",
    /^Mac app Can.t tell from a browser/,
    "Chooses the Mac app as the capture host; capability truth is 'cannot tell' in a browser",
    "dom",
    "selection moves; 'Not known' lines shown, never 'Installed'; start posts the Mac-host sources",
    "setup host Mac app",
  ],
  [
    "web.setup.host-browser",
    "setup",
    "radio",
    /^This browser only/,
    "Chooses this browser: hears you (dictation), cannot hear the other side, sees the screen after a share click",
    "dom",
    "selection moves; the can't-hear-app-audio warning shows and App audio defaults off; the started row's sources are microphone and screen",
    "setup host this browser only",
  ],
  [
    "web.setup.source-microphone",
    "setup",
    "switch",
    "Microphone",
    "Captures your voice",
    "server",
    "session row sources contain microphone only when on",
    "setup source Microphone",
  ],
  [
    "web.setup.source-app-audio",
    "setup",
    "switch",
    "App audio",
    "Captures the other side of the call",
    "server",
    "session row sources contain application-audio only when on",
    "setup source App audio",
  ],
  [
    "web.setup.source-screen",
    "setup",
    "switch",
    "Screen",
    "Captures screenshots",
    "server",
    "session row sources contain screen only when on",
    "setup source Screen",
  ],
  [
    "web.setup.live-assistance",
    "setup",
    "switch",
    "Live assistance",
    "Drafts answers to questions it hears",
    "server",
    "off: no draft-answer action is ever created for a heard question",
    "setup live assistance off",
  ],
  [
    "web.setup.import-matrix",
    "setup",
    "button",
    "Import one in Briefings",
    "Takes you to Briefings to import an experience matrix",
    "navigation",
    "view changes to briefings",
    "setup import matrix",
  ],
  [
    "web.setup.policy-remote",
    "setup",
    "radio",
    "Allow remote",
    "Remote models may be used",
    "server",
    "row processing_policy permitted_remote; model calls go through the agent runtime",
    "setup policy Allow remote",
  ],
  [
    "web.setup.policy-device",
    "setup",
    "radio",
    "Device only",
    "Only a model on this device is used",
    "server",
    "row processing_policy device_only; calls go to the direct device model, none to the agent runtime",
    "setup policy Device only",
  ],
  [
    "web.setup.retention-delete",
    "setup",
    "radio",
    "Delete at end",
    "Session records are deleted shortly after End",
    "server",
    "retention_mode delete_at_end; purge removes rows after End",
    "setup retention Delete at end",
  ],
  [
    "web.setup.retention-30",
    "setup",
    "radio",
    "30 days",
    "Records kept 30 days",
    "server",
    "retention_mode thirty_days",
    "setup retention 30 days",
  ],
  [
    "web.setup.retention-until",
    "setup",
    "radio",
    "Until I delete",
    "Records kept until you delete them",
    "server",
    "retention_mode until_deleted",
    "setup retention Until I delete",
  ],
  [
    "web.setup.start",
    "setup",
    "button",
    "Start session",
    "Starts a live session (disabled until what-for, consent and a source are chosen, with the reason shown)",
    "server",
    "interview.active_sessions row with status active",
    SMOKE_START,
  ],

  // ---- Live: session bar --------------------------------------------------
  [
    "web.bar.pause",
    "live-bar",
    "button",
    "Pause",
    "Pauses the session",
    "server",
    "row status paused; capture stops",
    "web session bar Pause",
  ],
  [
    "web.bar.resume",
    "live-bar",
    "button",
    "Resume",
    "Resumes the session",
    "server",
    "row status active",
    "web session bar Resume",
  ],
  [
    "web.bar.end",
    "live-bar",
    "button",
    "End",
    "Ends the session after confirmation",
    "server",
    "opens the confirm dialog; nothing changes on the server until End session is confirmed",
    SMOKE_END,
  ],
  [
    "web.end.keep-going",
    "end-dialog",
    "button",
    "Keep going",
    "Closes the dialog and keeps the session",
    "server",
    "row stays active",
    "web session bar End and Keep going",
  ],
  [
    "web.end.confirm",
    "end-dialog",
    "button",
    "End session",
    "Ends the session: capture stops, running work is cancelled, later results are discarded",
    "server",
    "row status ended, ended_at set; the ended view shows",
    SMOKE_END,
  ],

  // ---- Live: task panels ---------------------------------------------------
  [
    "web.task.chip",
    "tasks",
    "button",
    /^T\d+ · /,
    "Selects that task (earlier tasks are labelled; Back to current returns)",
    "dom",
    "the task article switches to that task and the follow-up placeholder names it",
  ],
  [
    "web.task.revisions",
    "task",
    "button",
    /^Revisions: rev \d+ of \d+$/,
    "Lists every revision of the task, newest first, the current one marked",
    "dom",
    "the list opens with the current revision marked and Outdated on older ones; Escape closes it and returns focus",
  ],
  [
    "web.task.revision",
    "task",
    "menuitemradio",
    /rev \d+/,
    "Shows that revision of the task (view-only)",
    "dom",
    "the answer, code, constraints and the task's single chat or transcript row switch to that revision; a follow-up still targets the current one",
  ],
  [
    "web.task.no-question-note",
    "transcript",
    "status",
    /captured: no question found|captures with no question|^No question found$/,
    "A capture that showed no interview question is a note, not a task",
    "dom",
    "a scripted no-question capture adds one muted note row (no T number, no chip, no answer bubble, the draft never repeated) and the server still holds the observation",
  ],
  // PENDING on the web: the Auto hold is proven only on the native panel
  // (native.auto.no-question-hold), which scripts a screen change through the host shim; Chromium's fake screen cannot be changed on cue, so a web spec could not tell the hold from an unchanged screen.
  [
    "web.auto.no-question-hold",
    "task",
    "status",
    /^No question on screen\. Auto is holding until the screen changes\.$|^No question found in the last capture\.$/,
    "Auto holds after a no-question capture until the screen changes (Manual says what the last capture found)",
    "server",
    "after a no-question result no further automatic capture is posted until the screen changes substantially or the cooldown passes; a manual capture is always posted",
  ],
  [
    "web.task.back-newest",
    "task",
    "button",
    /^Back to T\d+$/,
    "Goes back to the newest real task",
    "dom",
    "with a no-question capture newer than the newest real task, Back lands on that real task; with no real task the empty state shows",
  ],
  [
    "web.task.view-answer",
    "task",
    "tab",
    "Answer",
    "Shows the suggested answer",
    "dom",
    "answer tabpanel visible",
  ],
  [
    "web.task.view-code",
    "task",
    "tab",
    "Code",
    "Shows the code draft and test results",
    "dom",
    "code tabpanel visible with the scripted code and honest verification state",
  ],
  [
    "web.task.copy-answer",
    "task",
    "button",
    "Copy answer",
    "Copies the suggested answer",
    "clipboard",
    "navigator.clipboard text equals the draft; 'Copied' only after success",
  ],
  [
    "web.task.add-screenshot",
    "task",
    "button",
    "Add another screenshot",
    "Adds a screenshot to the selected task because context looks missing",
    "server",
    "capture revises the same task (revision + 1)",
  ],
  [
    "web.task.add-context",
    "task",
    "button",
    "Add context",
    "Focuses the follow-up box for the selected task",
    "dom",
    "the follow-up textbox is focused",
  ],
  [
    "web.task.looks-complete",
    "task",
    "button",
    "Looks complete",
    "Dismisses the missing-context prompt",
    "dom",
    "the strip hides and stays hidden after reload",
  ],

  // ---- Live: session details ------------------------------------------------
  [
    "web.tabs.transcript",
    "tabs",
    "tab",
    "Transcript",
    "Shows what was heard and typed",
    "dom",
    "transcript tabpanel visible",
  ],
  [
    "web.tabs.activity",
    "tabs",
    "tab",
    "Activity",
    "Shows activity such as captures and analyses",
    "dom",
    "the Runs list names each analysis run with its task and revision and how it ended (Answer draft, T1 · rev 1, Published), and the panel names the profile and policy",
    "device-only: a heard question is answered by the on-device model",
  ],
  [
    "web.tabs.sources",
    "tabs",
    "tab",
    "Sources",
    "Shows source health, pairing, processing and retention",
    "dom",
    "sources tabpanel visible",
    "sources tab: with no companion contact",
  ],
  [
    "web.sources.pair-show",
    "sources",
    "button",
    /^(Show|Hide)$/,
    "Reveals or masks the pairing credential",
    "dom",
    "the masked code changes to the real credential and back",
    "pairing Show and Hide",
  ],
  [
    "web.sources.pair-copy",
    "sources",
    "button",
    "Copy",
    "Copies the pairing credential",
    "clipboard",
    "clipboard equals the credential returned by the start response",
    "pairing Copy",
  ],
  [
    "web.sources.pair-renew",
    "sources",
    "button",
    "Renew",
    "Renews the credential",
    "server",
    "credential_expires_at moves later; the displayed expiry changes",
    "pairing Renew",
  ],
  [
    "web.sources.pair-revoke",
    "sources",
    "button",
    "Revoke",
    "Revokes the credential",
    "server",
    "credential_revoked_at set; the companion's ingest is refused",
    "pairing Revoke",
  ],
  [
    "web.sources.pair-dismiss",
    "sources",
    "button",
    "Dismiss",
    "Hides the credential panel; Studio will not show it again",
    "dom",
    "panel removed; no way to re-read the value",
    "pairing Dismiss",
  ],
  [
    "web.sources.device-only",
    "sources",
    "button",
    "Switch to this Mac only",
    "Tightens processing to device-only, one-way",
    "server",
    "row processing_policy device_only after confirmation; the control disappears",
    "Switch to this Mac only: cancelling",
  ],
  [
    "web.sources.revoke-confirm",
    "sources",
    "button",
    /^(Revoke and pause|Confirm revoke)$/,
    "Confirms revoking the credential (and pausing the session)",
    "server",
    "credential_revoked_at set, session paused, the companion's ingest refused",
    "pairing Revoke",
  ],
  [
    "web.sources.revoke-keep",
    "sources",
    "button",
    "Keep it",
    "Backs out of revoking: the credential stays valid",
    "server",
    "credential_revoked_at stays null and the companion is still accepted",
    "pairing Revoke",
  ],
  [
    "web.sources.confirm-cancel",
    "sources",
    "button",
    "Cancel",
    "Backs out of a one-way change (Switch to this Mac only, Shorten retention)",
    "server",
    "the session row keeps its policy and retention",
    "Switch to this Mac only: cancelling",
  ],
  [
    "web.sources.retention-shorten",
    "sources",
    "button",
    /^Shorten to /,
    "Shortens retention one way, after confirmation",
    "server",
    "retention_mode moves to the shorter mode; lengthening is refused",
    "retention shorten on the Sources tab",
  ],

  // ---- Code panel (the Code tab of a coding task) -------------------------------
  [
    "web.code.tab-solution",
    "code",
    "tab",
    "Solution",
    "Shows the solution code",
    "dom",
    "the editor shows the scripted solution",
  ],
  [
    "web.code.tab-usage",
    "code",
    "tab",
    "Usage",
    "Shows the usage example",
    "dom",
    "the editor shows the usage code",
  ],
  [
    "web.code.tab-tests",
    "code",
    "tab",
    "Tests",
    "Shows the tests",
    "dom",
    "the editor shows the scripted test code",
  ],
  [
    "web.code.wrap",
    "code",
    "button",
    "Wrap",
    "Toggles line wrapping",
    "dom",
    "the editor's white-space style flips",
  ],
  [
    "web.code.copy-all",
    "code",
    "button",
    "Copy all",
    "Copies the whole code",
    "clipboard",
    "clipboard holds the solution, usage and tests as shown",
  ],
  [
    "web.code.run",
    "code",
    "button",
    "Run",
    "Runs the code in the sandbox",
    "server",
    "a run request reaches the code runner and the Output shows its result, or an honest 'runner not available'",
  ],
  [
    "web.code.editor",
    "code",
    "textbox",
    "",
    "Edits the code",
    "dom",
    "typing changes the code that Copy all and Run use",
  ],
  [
    "web.code.results",
    "code",
    "button",
    /^Results/,
    "Shows test results ('Not run yet' until a run)",
    "dom",
    "the results panel opens; counts match the server's reported results",
  ],
  [
    "web.code.tab-output",
    "code",
    "tab",
    "Output",
    "Shows the run output",
    "dom",
    "the output panel is visible",
  ],
  [
    "web.code.open-workspace",
    "code",
    "button",
    "Open in Workspace",
    "Opens the draft in Workspace",
    "navigation",
    "URL becomes the workspace route for the draft",
  ],

  // ---- Ended view -----------------------------------------------------------
  [
    "web.ended.copy-draft",
    "ended",
    "button",
    /^Copy Answer draft \d+$/,
    "Copies that draft",
    "clipboard",
    "clipboard text equals the draft",
  ],
  [
    "web.ended.open-workspace",
    "ended",
    "button",
    "Open Workspace draft",
    "Opens the code draft in Workspace",
    "navigation",
    "URL becomes the workspace route for the draft",
  ],
  [
    "web.ended.history",
    "ended",
    "button",
    "Open session history",
    "Opens the paged session history",
    "dom",
    "the history list shows this session from the server's list route",
    "web ended Open session history",
  ],
  [
    "web.ended.delete",
    "ended",
    "button",
    "Delete session data",
    "Deletes the session's data",
    "server",
    "purge states shown until purged_at is set; rows and artifacts removed",
    "web ended Delete session data",
  ],
  [
    "web.ended.start-another",
    "ended",
    "button",
    "Start another session",
    "Returns to setup",
    "dom",
    "the setup page shows with no session carried over",
    "web ended Start another session",
  ],
]);

export const NATIVE_CLAIMS: Claim[] = make("native", [
  ...screenshotRows("native"),
  ...captureProblemRows("native"),
  // ---- Consent / empty ------------------------------------------------------
  [
    "native.consent.review",
    "consent",
    "button",
    "Review consent",
    "Opens consent review in the browser",
    "bridge",
    "the shell's consent bridge (`studioHost.consent.open`) is called; nothing starts until consent is granted",
    "host consent: with no session the start screen asks the shell",
  ],

  // ---- Toolbar: window dots -------------------------------------------------
  [
    "native.dot.red",
    "toolbar",
    "button",
    "Quit Interview Studio",
    "Quits the app after a confirmation; the session stays on the server",
    "bridge",
    "pressing it only asks (alertdialog with Cancel and Quit); quit is recorded once, only after Quit is confirmed",
    "native red dot Quit",
  ],
  [
    "native.dot.yellow",
    "toolbar",
    "button",
    "Hide window",
    "Hides the window; a live session pauses first",
    "bridge",
    "the session row is paused and setVisible(false) is recorded",
    "native yellow dot Hide window",
  ],
  [
    "native.dot.green",
    "toolbar",
    "button",
    /^Full screen: click/,
    "Click for full screen; click again to leave it",
    "bridge",
    "setFullScreen(on: true) is recorded, then setFullScreen(on: false)",
    "native green dot Full screen",
  ],

  // ---- Toolbar: controls ---------------------------------------------------
  [
    "native.tool.analyze",
    "toolbar",
    "button",
    /^Analyze screen( .*)?$/,
    "Captures the screen and analyzes it as a new task",
    "bridge",
    "captureScreen recorded, then a draft-answer action for a new task on the server",
  ],
  [
    "native.tool.mode",
    "toolbar",
    "button",
    /^Capture mode: (Auto|Manual)$/,
    "Opens the Auto/Manual menu",
    "dom",
    "menu with Auto, Manual and the add-screen item opens",
    "native Capture mode menu",
  ],
  [
    "native.tool.mic",
    "toolbar",
    "button",
    /^(Stop|Start) microphone$/,
    "Starts or stops the microphone",
    "bridge",
    "engine.start/stop recorded with the microphone source; the pressed state follows",
    "stop the native engine while Auto is on",
  ],
  [
    "native.tool.style",
    "toolbar",
    "button",
    /^Answer style:/,
    "Opens the answer-style list",
    "dom",
    "the page's single skill owner changes the label and the next request's skill",
    "native Answer style menu",
  ],
  [
    "native.tool.chat",
    "toolbar",
    "button",
    "Chat",
    "Shows or hides the Chat pane",
    "dom",
    "the chat pane and message box appear/disappear",
    "native pane toggles Chat, Answer and Code",
  ],
  [
    "native.tool.answer",
    "toolbar",
    "button",
    "Answer",
    "Shows or hides the Answer pane",
    "dom",
    "the answer pane appears/disappears",
    "native pane toggles Chat, Answer and Code",
  ],
  [
    "native.tool.code",
    "toolbar",
    "button",
    "Code",
    "Shows or hides the Code pane",
    "dom",
    "the code pane appears/disappears",
    "native pane toggles Chat, Answer and Code",
  ],
  [
    "native.tool.screen",
    "toolbar",
    "button",
    /^Screen to capture: /,
    "The chevron attached to the capture button: opens the screen menu; its name says 'Following your browser' or 'Pinned: Display 2 of 3'; a pin dot shows on it while pinned",
    "bridge",
    "listDisplays recorded only after it opens; the name and pin dot follow setCaptureDisplay",
  ],
  [
    "native.tool.capture-target",
    "toolbar",
    "button",
    "Analyze screen",
    "The capture button's tooltip says what it does AND the target ('...: following your browser, ⌘⇧S' or '...: Display 2 of 3 (pinned), ⌘⇧S'); a right-click or ArrowDown on it opens the screen menu; a plain click only captures",
    "dom",
    "title follows the pin; contextmenu/ArrowDown open the 'Screen to capture' menu; no separate monitor icon and no display-name chip",
  ],
  [
    "native.tool.see-through",
    "toolbar",
    "button",
    "See-through",
    "ONE control for the clear glass and the pass-through of clicks over empty glass (⌘⇧I); the old interactive/click-through icon and the Transparent background button are gone",
    "bridge",
    "on: the panel root gains data-glass=clear (persists across reload) and setHitRegions({regions:[...]}) is recorded including the toolbar's rectangle; off: setHitRegions(null); ⌘⇧I (see-through.toggle) flips it; the tooltip says what is on",
    "native host See-through: on sends setHitRegions",
  ],
  [
    "native.tool.keys",
    "toolbar",
    "button",
    "Keyboard shortcuts",
    "Lists the shortcuts",
    "dom",
    "popover lists the typed shortcut table with the platform chords",
    "keys popover: lists every shortcut",
  ],

  // ---- Capture-mode menu and style menu --------------------------------------
  [
    "native.mode.auto",
    "mode-menu",
    "menuitemradio",
    /^Auto /,
    "Re-analyses when the screen changes, every 8 s, at most 120 per session",
    "bridge",
    "screenWatchStart recorded; a changed screen event creates a task",
  ],
  [
    "native.mode.manual",
    "mode-menu",
    "menuitemradio",
    /^Manual /,
    "Analyses only when you press",
    "bridge",
    "screenWatchStop recorded; no task without a press",
  ],
  [
    "native.mode.add-screen",
    "mode-menu",
    "menuitem",
    /^Add screen to this problem/,
    "Adds a capture to the selected task",
    "server",
    "same task_id gets revision + 1; disabled with 'Needs a task first' before any task",
  ],
  [
    "native.screen.follow",
    "screen-menu",
    "menuitemradio",
    /^Follow my browser/,
    "Capture the display your browser is on (the default); unpins",
    "bridge",
    "setCaptureDisplay(null) recorded; the pin dot disappears and the tooltip says Following your browser",
  ],
  [
    "native.screen.display",
    "screen-menu",
    "menuitemradio",
    /, \d+ of \d+$/,
    "Pins capture to this display; its live thumbnail shows what is on it",
    "bridge",
    "setCaptureDisplay(<id>) recorded; the pin dot shows, the next capture reports that display, thumbnails stop refreshing when the menu closes",
  ],
  [
    "native.screen.pin-dropped",
    "toolbar",
    "status",
    "The pinned display was disconnected. Following your browser again.",
    "Says once that the pinned display is gone and capture follows the browser again",
    "dom",
    "after the shim drops the pin (setDisplays without it), one toast shows and the pin dot clears",
  ],
  [
    "native.style.item",
    "style-menu",
    "menuitemradio",
    /.*/,
    "Chooses the answer style (skill)",
    "dom",
    "toolbar label changes; the next request carries that skill",
    "native Answer style menu",
  ],

  // ---- Strip / chat -----------------------------------------------------------
  [
    "native.chat.message",
    "chat",
    "textbox",
    "Message",
    "Ask anything, or add context (the shell's chat.focus intent puts the cursor here)",
    "dom",
    "chat.focus focuses it; the placeholder names the selected task",
    SMOKE_NATIVE,
  ],
  [
    "native.chat.send",
    "chat",
    "button",
    "Send message",
    "Sends the message to the selected task",
    "server",
    "owner.input observation and a new revision of the selected task",
  ],
  [
    "native.chat.entry",
    "chat",
    "button",
    /^Studio · T\d+/,
    "Selects the task that answer belongs to",
    "dom",
    "the answer pane shows that task",
  ],
  [
    "native.task.chip",
    "task",
    "button",
    /^T\d+ · /,
    "Selects that task (earlier-task label, Back to current)",
    "dom",
    "answer pane switches to that task",
  ],
  [
    "native.task.revisions",
    "task",
    "button",
    /^Revisions: rev \d+ of \d+$/,
    "Lists every revision of the task, newest first, the current one marked",
    "dom",
    "the list opens with the current revision marked and Outdated on older ones; Escape closes it and returns focus",
  ],
  [
    "native.task.revision",
    "task",
    "menuitemradio",
    /rev \d+/,
    "Shows that revision of the task (view-only)",
    "dom",
    "the answer, code, constraints and the task's single chat or transcript row switch to that revision; a follow-up still targets the current one",
  ],
  [
    "native.task.no-question-note",
    "transcript",
    "status",
    /captured: no question found|captures with no question|^No question found$/,
    "A capture that showed no interview question is a note, not a task",
    "dom",
    "a scripted no-question capture adds one muted note row (no T number, no chip, no answer bubble, the draft never repeated) and the server still holds the observation",
  ],
  [
    "native.auto.no-question-hold",
    "task",
    "status",
    /^No question on screen\. Auto is holding until the screen changes\.$|^No question found in the last capture\.$/,
    "Auto holds after a no-question capture until the screen changes (Manual says what the last capture found)",
    "server",
    "after a no-question result no further automatic capture is posted until the screen changes substantially or the cooldown passes; a manual capture is always posted",
  ],
  [
    "native.task.back-newest",
    "task",
    "button",
    /^Back to T\d+$/,
    "Goes back to the newest real task",
    "dom",
    "with a no-question capture newer than the newest real task, Back lands on that real task; with no real task the empty state shows",
  ],
  [
    "native.task.copy",
    "task",
    "button",
    "Copy answer",
    "Copies the answer",
    "clipboard",
    "clipboard equals the draft",
  ],
  [
    "native.pane.analyze",
    "answer-pane",
    "button",
    /^Analyze screen/,
    "Analyzes the screen",
    "bridge",
    "same as the toolbar control",
    "native answer pane empty state",
  ],

  // ---- Footer ----------------------------------------------------------------
  [
    "native.footer.pause",
    "footer",
    "button",
    "Pause session",
    "Pauses the session",
    "server",
    "row status paused; capture and engine stop",
    "native footer Pause and Resume",
  ],
  [
    "native.footer.resume",
    "footer",
    "button",
    /^Resume( session)?$/,
    "Resumes the session",
    "server",
    "row status active",
    "native footer Pause and Resume",
  ],
  [
    "native.footer.end",
    "footer",
    "button",
    "End session",
    "Opens the End confirmation",
    "dom",
    "inline confirmation with End now / Keep going",
    "native footer End session",
  ],
  [
    "native.footer.end-now",
    "footer",
    "button",
    "End now",
    "Ends the session",
    "server",
    "row status ended; the ended card replaces the controls",
    "native footer End session",
  ],
  [
    "native.footer.keep-going",
    "footer",
    "button",
    "Keep going",
    "Closes the confirmation",
    "dom",
    "the confirmation closes; row stays active",
    "native footer End session",
  ],

  // ---- Ended card ------------------------------------------------------------
  [
    "native.ended.summary",
    "ended",
    "button",
    "Open summary",
    "Opens the session summary in the browser",
    "bridge",
    "openExternal recorded with the web ended-view URL",
    "native ended card Open summary",
  ],
  [
    "native.ended.new",
    "ended",
    "button",
    "Start a new session",
    "Starts a new session",
    "server",
    "a second active_sessions row appears",
    "native ended card Start a new session",
  ],

  // ---- Settings window --------------------------------------------------------
  [
    "native.settings.close",
    "settings",
    "button",
    "Close",
    "Closes Settings",
    "bridge",
    "closeSettings recorded",
    "native Settings window Close and Quit",
  ],
  [
    "native.settings.quit",
    "settings",
    "button",
    "Quit",
    "Quits the app",
    "bridge",
    "quit recorded",
    "native Settings window Close and Quit",
  ],
  [
    "native.settings.skill",
    "settings",
    "combobox",
    "Active Skill",
    "Chooses the answer style",
    "dom",
    "the page's skill changes, shared with the panel toolbar",
    "native Settings window Active Skill and Coding Language",
  ],
  [
    "native.settings.language",
    "settings",
    "combobox",
    "Coding Language",
    "Chooses the coding language; unsupported ones say so",
    "dom",
    "only supported languages can be chosen",
    "native Settings window Active Skill and Coding Language",
  ],
  [
    "native.settings.option",
    "settings",
    "option",
    /.*/,
    "A choice in a Settings list",
    "dom",
    "selecting it changes the field",
    "native Settings window Active Skill and Coding Language",
  ],
]);

// ---- E-B3: controls the capture/tasks/tray/picker/window specs reach, and the
// specs that cover claims above. One table of id -> a substring of the title of
// the spec that asserts the effect; applied here so the rows stay readable.
WEB_CLAIMS.push(
  ...make("web", [
    [
      "web.transcript.download",
      "transcript",
      "link",
      "Download",
      "Downloads that screenshot",
      "server",
      "the href is the session's screenshot route and it serves the stored image, byte for byte",
    ],
  ]),
);

// ---- Account: sign-in states, the sidebar account menu, sign-out ----------------
WEB_CLAIMS.push(
  ...make("web", [
    [
      "web.account.footer",
      "shell",
      "button",
      /^Account: /,
      "Opens the account menu for the signed-in member named on it",
      "dom",
      "a menu opens (aria-expanded true) and Escape closes it, returning focus to this button",
      "web account: the footer names the member",
    ],
    [
      "web.account.connected",
      "account-menu",
      "menuitem",
      "Connected accounts",
      "Opens the workspace's connected accounts page",
      "navigation",
      "URL becomes /t/local/settings/integrations and its heading shows",
      "web account: Connected accounts and Sign in with an account",
    ],
    [
      "web.account.sign-in-with-account",
      "account-menu",
      "menuitem",
      "Sign in with an account",
      "Local user only: goes to sign-in, returning to the page the person was on",
      "navigation",
      "URL becomes /sign-in?next=<the current page> and the banner names that page",
      "web account: Connected accounts and Sign in with an account",
    ],
    [
      "web.account.sign-out",
      "account-menu",
      "menuitem",
      "Sign out",
      "Asks to confirm signing out of this browser",
      "dom",
      "an alertdialog opens with Cancel focused",
      "web account: signing out without a live session",
    ],
    [
      "web.account.sign-out-cancel",
      "sign-out-dialog",
      "button",
      "Cancel",
      "Keeps the person signed in",
      "dom",
      "the dialog closes, focus returns to the footer and a reload is still signed in",
      "web account: signing out without a live session",
    ],
    [
      "web.account.sign-out-confirm",
      "sign-out-dialog",
      "button",
      /^(Sign out|End session and sign out)$/,
      "Ends this browser's session (and a running live session first), then shows the signed-out page",
      "server",
      "the live session row is ended, /api/auth/session has no user, and the next page visit asks to sign in",
      "web account: signing out with a live session",
    ],
    [
      "web.account.welcome-dismiss",
      "shell",
      "button",
      "Dismiss welcome message",
      "Hides the one-time welcome after signing in",
      "dom",
      "the banner is removed",
      "web account: the welcome banner shows once",
    ],
    [
      "web.signedout.again",
      "signed-out",
      "link",
      "Sign in again",
      "Goes to the sign-in page",
      "navigation",
      "URL becomes /sign-in",
      "web account: signing out without a live session",
    ],
  ]),
);

NATIVE_CLAIMS.push(
  ...make("native", [
    [
      "native.code.tests-handle",
      "code-pane",
      "button",
      "Tests",
      "Opens or closes the Tests drawer (|>| / |<|) on the code pane's left edge; the choice is remembered",
      "dom",
      "aria-expanded flips, the drawer is hidden and inert while closed, and the choice survives a reload",
      "native Tests drawer: |>| opens",
    ],
    [
      "native.tool.stop",
      "toolbar",
      "button",
      "Stop",
      "While work runs, the capture button stops all analysis; the session stays open",
      "server",
      "the in-flight action is suppressed (owner_stopped), its model call cancelled, the session stays active",
      "native Stop: while work runs",
    ],
    [
      "native.code.solution",
      "code-pane",
      "textbox",
      "Solution",
      "Shows the generated solution (read-only)",
      "dom",
      "the editor holds the scripted solution text",
      "native Code pane: a clean real run",
    ],
    [
      "native.code.test-source",
      "tests-drawer",
      "textbox",
      "Generated test source",
      "Shows the generated test source (read-only)",
      "dom",
      "the editor holds the test the real runner ran",
      "native Tests drawer: |>| opens",
    ],
    [
      "native.code.copy-code",
      "code-pane",
      "button",
      /^(Copy code|Copied)$/,
      "Copies the solution",
      "clipboard",
      "the clipboard holds the solution text; the label says Copied only after the write",
      "native Code pane: a clean real run",
    ],
    [
      "native.code.copy-tests",
      "tests-drawer",
      "button",
      /^(Copy tests|Copied)$/,
      "Copies the generated test source",
      "clipboard",
      "the clipboard holds the test source the runner ran",
      "native Tests drawer Copy tests",
    ],
    [
      "native.code.goto-line",
      "tests-drawer",
      "button",
      /^Go to line \d+ \((solution|tests)\)$/,
      "Goes to the line a failed test points at",
      "dom",
      "that line of the named editor is marked",
      "native Code pane with a failing generated test",
    ],
    [
      "native.code.problem-line",
      "code-pane",
      "button",
      /^Line \d+(:\d+)?$/,
      "Goes to the line of a syntax problem",
      "dom",
      "that line of the solution is marked",
      "native Code pane with a syntax error",
    ],
    [
      "native.dot.size-menu",
      "size-menu",
      "menuitemradio",
      /^(Normal|Mini player|Full screen)\b/,
      "Chooses the window size: the normal panes, the small Mini player card, or full screen",
      "bridge",
      "setWindowSize (440 x 190) is recorded for the Mini player and the card replaces the panes; Normal returns the wide size",
      "native Mini player",
    ],
    [
      "native.mini.back",
      "mini-player",
      "button",
      "Back to normal",
      "Returns from the Mini player to the normal window",
      "bridge",
      "the panes return and a wide setWindowSize is recorded",
      "native Mini player",
    ],
    [
      "native.mini.stop",
      "mini-player",
      "button",
      "Stop analysis",
      "Stops the running work from the small card",
      "server",
      "the in-flight action is suppressed (owner_stopped)",
      "native Mini player Stop analysis",
    ],
    [
      "native.mini.pause",
      "mini-player",
      "button",
      /^(Pause|Resume)$/,
      "Pauses or resumes the session from the small card",
      "server",
      "the session row becomes paused, then active",
      "native Mini player",
    ],
  ]),
);

// ---- Native sign-in and start screens: signed out, waiting, this Mac, idle, account menu --
NATIVE_CLAIMS.push(
  ...make("native", [
    [
      "native.signin.google",
      "sign-in",
      "button",
      "Continue with Google",
      "Signs in with Google in your default browser (the window waits and updates by itself)",
      "bridge",
      "the shell's account bridge records signIn with provider google, and the waiting screen names Google",
      "sign-in Google: the click asks the shell for the browser",
    ],
    [
      "native.signin.linkedin",
      "sign-in",
      "button",
      "Continue with LinkedIn",
      "Signs in with LinkedIn in your default browser",
      "bridge",
      "the shell's account bridge records signIn with provider linkedin, and the waiting screen names LinkedIn",
      "sign-in a timed-out browser attempt returns to the choices",
    ],
    [
      "native.signin.local",
      "sign-in",
      "button",
      "Continue on this Mac, no account",
      "Uses Studio on this Mac only: no account, no password (offered only where Studio runs on this computer)",
      "dom",
      "the confirm step opens with its facts; no browser is asked for",
      "sign-in this Mac: confirm step with true facts",
    ],
    [
      "native.signin.local-back",
      "sign-in-local",
      "button",
      "Back",
      "Returns from the local-profile step to the sign-in choices",
      "dom",
      "the sign-in choices show again",
      "sign-in this Mac: confirm step with true facts",
    ],
    [
      "native.signin.local-continue",
      "sign-in-local",
      "button",
      "Continue on this Mac",
      "Signs in as the local profile inside this window",
      "navigation",
      "Studio's own sign-in sets the session and the window goes to the compact panel with its idle start screen",
      "sign-in this Mac: confirm step with true facts",
    ],
    [
      "native.signin.reopen",
      "sign-in-waiting",
      "button",
      "Open browser again",
      "Opens the same sign-in in your default browser again",
      "bridge",
      "the shell's account bridge records reopenSignIn",
      "sign-in Google: the click asks the shell for the browser",
    ],
    [
      "native.signin.copy-link",
      "sign-in-waiting",
      "button",
      "Copy link",
      "Copies the sign-in link (the shell copies it; the page never sees it)",
      "bridge",
      "the shell's account bridge records copySignInLink and the window says the link was copied",
      "sign-in Google: the click asks the shell for the browser",
    ],
    [
      "native.signin.cancel",
      "sign-in-waiting",
      "button",
      "Cancel",
      "Gives up waiting for the browser (the same name as the crop editor's Cancel, which the inventory matches first)",
      "bridge",
      "the shell's account bridge records cancelSignIn and the sign-in choices return",
      "sign-in Google: the click asks the shell for the browser",
    ],
    [
      "native.chip.account",
      "toolbar",
      "button",
      /^Account: /,
      "Opens the account menu for who is signed in (this Mac, or the account's first name)",
      "dom",
      "a menu opens naming the account, with Open Studio on the web, Settings and the sign-out",
      "sign-in account menu: the chip names this Mac",
    ],
    [
      "native.chip.open-studio",
      "account-menu",
      "menuitem",
      "Open Studio on the web",
      "Opens Studio on the web in your browser",
      "bridge",
      "the shell's openExternal is called with the workspace's Live page address",
      "sign-in account menu: the chip names this Mac",
    ],
    [
      "native.chip.settings",
      "account-menu",
      "menuitem",
      "Settings",
      "Opens the Settings window",
      "bridge",
      "the shell's presentation openSettings is recorded",
      "sign-in account menu: the chip names this Mac",
    ],
    [
      "native.chip.sign-in-with",
      "account-menu",
      "menuitem",
      "Sign in with Google or LinkedIn",
      "Local profile only: leaves this Mac's local profile and returns to the sign-in choices (an account is a separate profile)",
      "bridge",
      "the shell's account bridge records signOut",
      "sign-in account menu: the chip names this Mac",
    ],
    [
      "native.chip.sign-out",
      "account-menu",
      "menuitem",
      /^Sign out/,
      "Signs out on this Mac only: the window forgets the session, capture stops, and the sign-in screen shows",
      "bridge",
      "the shell's account bridge records signOut",
      "sign-in account menu: the chip names this Mac",
    ],
    [
      "native.start.target",
      "start",
      "radio",
      /./,
      "Chooses what the session is for: the next interview, or Rehearsal",
      "server",
      "the started session row carries the chosen target (a Rehearsal has a rehearsal run id)",
      "sign-in Start hands over to the live window",
    ],
    [
      "native.start.agree",
      "start",
      "checkbox",
      /^Everyone has agreed/,
      "Confirms everyone agreed to recording and AI assistance (an interview only)",
      "dom",
      "Start stays blocked with 'Confirm everyone has agreed' until it is checked; covered at the unit level (start-panel.test.tsx), the e2e stack has no interview to start for",
    ],
    [
      "native.start.allow",
      "start",
      "button",
      "Allow…",
      "Opens the macOS privacy pane for a permission that is not allowed yet",
      "bridge",
      "the shell's openExternal is called with the Screen Recording pane address",
      "sign-in idle: the start screen waits for Start",
    ],
    [
      "native.start.go",
      "start",
      "button",
      "Start session",
      "Starts the session (blocked, with the reason, until the Mac's permissions and the agreement are in place)",
      "server",
      "an interview.active_sessions row with status active, only after the press",
      "sign-in Start hands over to the live window",
    ],
    [
      "native.start.setup-link",
      "start",
      "button",
      "Set up in Studio on the web",
      "Opens Studio on the web in your browser, where a session is set up in full",
      "bridge",
      "the shell's openExternal is called with the workspace's Live page address",
      "sign-in idle: the start screen waits for Start",
    ],
  ]),
);

const COVERED_BY: Record<string, string> = {
  "web.task.view-answer": "web coding answer: Answer and Code views",
  "web.task.view-code": "web coding answer: Answer and Code views",
  "web.task.copy-answer": "web Copy answer",
  "web.screenshots.toggle": "screenshots icon and tray modes",
  "web.screenshots.thumb": "screenshots stored thumbnails",
  "web.screenshots.scroll": "screenshots stored thumbnails",
  "web.screenshots.add": "screenshots Add screenshot",
  "web.screenshots.intent": "screenshots intent Add to T1",
  "web.screenshots.apply": "screenshots Add screenshot",
  "web.screenshots.discard": "screenshots Remove and Discard",
  "web.screenshots.remove": "screenshots Remove and Discard",
  "web.screenshots.crop": "screenshots Crop:",
  "web.screenshots.crop-field": "screenshots Crop:",
  "web.screenshots.crop-handle": "screenshots crop handles",
  "web.screenshots.move": "screenshots reorder",
  "web.screenshots.viewer-zoom": "screenshots viewer:",
  "web.screenshots.viewer-close": "screenshots viewer:",
  "web.screenshots.viewer-crop": "screenshots viewer Crop",
  "native.tool.analyze": "native Analyze screen in Manual",
  "native.tool.capture-target": "native capture target",
  "web.code.open-workspace": "web code canvas Open in Workspace",
  "web.ended.copy-draft": "web ended Copy Answer draft",
  "web.ended.open-workspace": "web ended Open Workspace draft",
  "web.shell.nav-home": "web shell view buttons",
  "web.shell.nav-workspace": "web shell view buttons",
  "web.shell.nav-briefings": "web shell view buttons",
  "web.shell.nav-documents": "web shell view buttons",
  "web.shell.nav-knowledge": "web shell view buttons",
  "web.shell.nav-rehearsal": "web shell view buttons",
  "web.shell.nav-live": "web shell Live session dot",
  "web.shell.search": "web shell search",
  "web.shell.theme": "web shell theme",
  "web.shell.assistant": "web shell Assistant",
  "web.shell.presentations": "web shell Presentations",
  "web.code.run": "web code canvas Run",
  "web.code.tab-solution": "web code canvas: the file tabs",
  "web.code.tab-usage": "web code canvas: the file tabs",
  "web.code.tab-tests": "web code canvas: the file tabs",
  "web.code.wrap": "web code canvas: the file tabs",
  "web.code.copy-all": "web code canvas: the file tabs",
  "web.code.editor": "web code canvas: the file tabs",
  "web.code.results": "web code canvas: the file tabs",
  "web.code.tab-output": "web code canvas: the file tabs",
  "native.capture-problem.dismiss": "native capture problem permission-denied",
  "native.capture-problem.open-settings":
    "native capture problem permission-denied",
  "native.mode.auto": "native Capture mode menu",
  "native.mode.manual": "native Capture mode menu",
  "native.mode.add-screen": "native Add screen to T1",
  "native.chat.send": "native typed question",
  "native.chat.entry": "native chat entry",
  "native.task.chip": "native task chips and Back",
  "native.task.back-newest": "native no-question and Back",
  "native.task.copy": "native Copy answer",
  "native.task.revisions": "native Revisions",
  "native.task.revision": "native Revisions",
  "native.task.no-question-note": "native no-question in Manual",
  "native.auto.no-question-hold": "native Auto after a no-question capture",
  // The name and the pin dot follow setCaptureDisplay (the pin test); the
  // menu test proves listDisplays asks for thumbnails only while it is open.
  "native.tool.screen": "native screen picker pin: choosing a display",
  "native.screen.follow": "native screen picker pin",
  "native.screen.display": "native screen picker pin",
  "native.screen.pin-dropped": "native screen picker pin dropped",
  "native.screenshots.toggle": "screenshots icon and tray modes",
  "native.screenshots.thumb": "screenshots stored thumbnails",
  "native.screenshots.scroll": "screenshots stored thumbnails",
  "native.screenshots.add": "screenshots Add screenshot",
  "native.screenshots.intent": "screenshots intent Add to T1",
  "native.screenshots.apply": "screenshots Add screenshot",
  "native.screenshots.discard": "screenshots Remove and Discard",
  "native.screenshots.remove": "screenshots Remove and Discard",
  "native.screenshots.crop": "screenshots Crop:",
  "native.screenshots.crop-field": "screenshots Crop:",
  "native.screenshots.crop-handle": "screenshots crop handles",
  "native.screenshots.move": "screenshots reorder",
  "native.screenshots.viewer-zoom": "screenshots viewer:",
  "native.screenshots.viewer-close": "screenshots viewer:",
  "native.screenshots.viewer-crop": "screenshots viewer Crop",
};
// A claim names its spec in ONE place: a row's own `spec` or COVERED_BY. When
// both name a spec and they differ, the claims-coverage spec fails on it.
export const SPEC_DISAGREEMENTS: string[] = [];
for (const claim of [...WEB_CLAIMS, ...NATIVE_CLAIMS]) {
  const spec = COVERED_BY[claim.id];
  if (!spec) continue;
  if (claim.spec && claim.spec !== spec)
    SPEC_DISAGREEMENTS.push(
      `${claim.id}: row says "${claim.spec}", COVERED_BY says "${spec}"`,
    );
  else if (!claim.spec) {
    claim.status = "covered";
    claim.spec = spec;
  }
}

export const CLAIMS: Claim[] = [...WEB_CLAIMS, ...NATIVE_CLAIMS];

export function matches(claim: Claim, role: string, name: string): boolean {
  if (claim.role !== role) return false;
  return typeof claim.name === "string"
    ? claim.name === name
    : claim.name.test(name);
}

export const findClaim = (
  surface: Surface,
  role: string,
  name: string,
): Claim | undefined =>
  CLAIMS.find(
    (claim) => claim.surface === surface && matches(claim, role, name),
  );
