// The debt the application-boundary tripwires tolerate today (ADR-0042), one
// list per rule of scripts/application-boundaries.ts. Configuration, not
// suppression: scripts/application-boundaries.test.ts fails on anything that is
// not listed or is above its number, and also on a number above what exists,
// so each list can only shrink. When a refactor pays debt, lower the number in
// the same change; when a file is clean, delete its entry. Never raise a number
// to make a change pass: move the code to its layer instead
// (bionic/research/references/application-boundaries.md).
// Recompute every list from the current tree (at integration, or after a
// refactor; review the diff: a number that rose is a new violation):
//   pnpm boundaries:update
// GENERATED by that command; the comments come from RULES.

type Debt = Readonly<Record<string, number>>;

// (a) SQL text outside a repository, a schema declaration and
// packages/database: path -> statements. Each is a statement to move into a
// repository method (ADR-0042 point 1). ADR-0023 still decides which of them
// may stay raw there.
export const sqlOutsideRepositories: Debt = {
  "packages/platform-storage/src/bootstrap.ts": 4,
  "products/interview/src/backend/live-session/credential-lookup.ts": 1,
  "products/interview/src/backend/live-session/routes.ts": 2,
  "products/interview/src/backend/live-session/session-claim.ts": 2,
  "products/interview/src/backend/live-session/session-purge.ts": 2,
};
// (b) Query-builder chains and tenant transactions inside a route, a handler or
// a frontend file: path -> sites. The route delegates; the service owns the
// transaction (points 2 and 3).
export const persistenceInTransport: Debt = {
  "products/interview/src/backend/live-session/routes.ts": 1,
};
// (c) Route modules that import a table schema: path -> imports (point 2).
export const schemaImportsInTransport: Debt = {};
// (d) Product frontend files importing backend internals or a database package:
// path -> imports (point 7).
export const backendImportsInFrontend: Debt = {};
// (e-size) Backend modules over 400 lines: path -> a ceiling on its lines (its
// size when listed, rounded up to 25). A file may not grow past its ceiling; a
// ceiling more than ten percent above the real size is stale and must be
// lowered; under 400 lines the entry is deleted (point 8).
export const oversizedBackendModules: Debt = {
  "products/interview/src/backend/assistant/adapter.ts": 1050,
  "products/interview/src/backend/assistant/workspace.ts": 675,
  "products/interview/src/backend/brief/repository.ts": 1350,
  "products/interview/src/backend/brief/routes.ts": 450,
  "products/interview/src/backend/coach/coach.ts": 975,
  "products/interview/src/backend/coach/reply.ts": 425,
  "products/interview/src/backend/context-pack/bench-prepared.ts": 850,
  "products/interview/src/backend/context-pack/bench.ts": 425,
  "products/interview/src/backend/context-pack/brief-sources.ts": 550,
  "products/interview/src/backend/context-pack/eval/answers.ts": 800,
  "products/interview/src/backend/context-pack/eval/arms.ts": 475,
  "products/interview/src/backend/context-pack/eval/call-scenario.ts": 525,
  "products/interview/src/backend/context-pack/eval/retrieval.ts": 500,
  "products/interview/src/backend/context-pack/pack.ts": 875,
  "products/interview/src/backend/context-pack/prepare.ts": 875,
  "products/interview/src/backend/context-pack/recipe.ts": 775,
  "products/interview/src/backend/context-pack/sources.ts": 425,
  "products/interview/src/backend/documents/api.ts": 800,
  "products/interview/src/backend/documents/cast.ts": 625,
  "products/interview/src/backend/documents/document.service.ts": 1225,
  "products/interview/src/backend/documents/generate.ts": 750,
  "products/interview/src/backend/documents/repository.ts": 1175,
  "products/interview/src/backend/documents/template-intake.ts": 475,
  "products/interview/src/backend/documents/verify.ts": 425,
  "products/interview/src/backend/interview-backend.ts": 475,
  "products/interview/src/backend/live-session/assist-stage.ts": 1175,
  "products/interview/src/backend/live-session/claims.ts": 1000,
  "products/interview/src/backend/live-session/coding-path.ts": 450,
  "products/interview/src/backend/live-session/context-snapshot.ts": 500,
  "products/interview/src/backend/live-session/fenced-writes.ts": 675,
  "products/interview/src/backend/live-session/memory-session-world.ts": 450,
  "products/interview/src/backend/live-session/processor.ts": 575,
  "products/interview/src/backend/live-session/repository.ts": 675,
  "products/interview/src/backend/live-session/routes.ts": 850,
  "products/interview/src/backend/live-session/session-dispatch.ts": 775,
  "products/interview/src/backend/live-session/session-reads.ts": 525,
  "products/interview/src/backend/live-session/session-run.ts": 1475,
  "products/presentation/src/backend/api.ts": 450,
  "products/presentation/src/repositories/index.ts": 850,
};
// (e-mixed) Files mixing three or more of transport, service, persistence,
// contracts, integration and presentation: path -> how many (point 8).
export const mixedResponsibilities: Debt = {
  "products/interview/src/backend/documents/repository.ts": 3,
  "products/interview/src/backend/live-session/routes.ts": 3,
};
// (f) Hand-built UI per screen directory of the product frontends and apps/web:
// "directory metric" -> count, where the metric is a raw layout element, a
// className, an inline style, a CSS import, a stylesheet file or a raw
// input/select/textarea (point 7). The audit behind it is
// bionic/briefs/BRIEF-web-app-on-the-ui-library-only.md. Raw buttons, dialogs
// and tables stay with scripts/ui-migration-audit.ts.
export const handBuiltUi: Debt = {
  "apps/web/app/ className": 24,
  "apps/web/app/ cssImport": 5,
  "apps/web/app/ field": 4,
  "apps/web/app/ layout": 37,
  "apps/web/app/ style": 5,
  "apps/web/app/ stylesheet": 1,
  "apps/web/src/ className": 2,
  "apps/web/src/ layout": 2,
  "products/interview/src/frontend/ className": 63,
  "products/interview/src/frontend/ field": 1,
  "products/interview/src/frontend/ layout": 65,
  "products/interview/src/frontend/studio/ className": 54,
  "products/interview/src/frontend/studio/ field": 1,
  "products/interview/src/frontend/studio/ layout": 48,
  "products/interview/src/frontend/studio/ style": 2,
  "products/interview/src/frontend/studio/ stylesheet": 4,
  "products/interview/src/frontend/studio/account/ className": 24,
  "products/interview/src/frontend/studio/account/ layout": 21,
  "products/interview/src/frontend/studio/account/ stylesheet": 1,
  "products/interview/src/frontend/studio/briefings/ className": 236,
  "products/interview/src/frontend/studio/briefings/ field": 12,
  "products/interview/src/frontend/studio/briefings/ layout": 242,
  "products/interview/src/frontend/studio/briefings/ style": 2,
  "products/interview/src/frontend/studio/briefings/ stylesheet": 2,
  "products/interview/src/frontend/studio/documents/ className": 31,
  "products/interview/src/frontend/studio/documents/ field": 2,
  "products/interview/src/frontend/studio/documents/ layout": 26,
  "products/interview/src/frontend/studio/documents/ style": 17,
  "products/interview/src/frontend/studio/documents/ stylesheet": 1,
  "products/interview/src/frontend/studio/home/ className": 55,
  "products/interview/src/frontend/studio/home/ field": 7,
  "products/interview/src/frontend/studio/home/ layout": 56,
  "products/interview/src/frontend/studio/home/ style": 1,
  "products/interview/src/frontend/studio/home/ stylesheet": 1,
  "products/interview/src/frontend/studio/live/ className": 687,
  "products/interview/src/frontend/studio/live/ field": 8,
  "products/interview/src/frontend/studio/live/ layout": 710,
  "products/interview/src/frontend/studio/live/ style": 49,
  "products/interview/src/frontend/studio/live/ stylesheet": 15,
  "products/interview/src/frontend/studio/rehearsal/ className": 74,
  "products/interview/src/frontend/studio/rehearsal/ field": 5,
  "products/interview/src/frontend/studio/rehearsal/ layout": 84,
  "products/interview/src/frontend/studio/rehearsal/ style": 6,
  "products/interview/src/frontend/studio/rehearsal/ stylesheet": 1,
  "products/interview/src/frontend/studio/shared/ className": 2,
  "products/interview/src/frontend/studio/shared/ layout": 2,
  "products/interview/src/frontend/studio/shared/ style": 1,
  "products/interview/src/frontend/studio/workspace/ className": 128,
  "products/interview/src/frontend/studio/workspace/ field": 3,
  "products/interview/src/frontend/studio/workspace/ layout": 128,
  "products/interview/src/frontend/studio/workspace/ style": 2,
  "products/interview/src/frontend/studio/workspace/ stylesheet": 1,
  "products/interview/src/frontend/ui/ stylesheet": 1,
  "products/presentation/src/frontend/ className": 17,
  "products/presentation/src/frontend/ field": 2,
  "products/presentation/src/frontend/ layout": 30,
  "products/presentation/src/frontend/ style": 1,
  "products/presentation/src/frontend/ stylesheet": 1,
  "products/presentation/src/frontend/pages/ className": 101,
  "products/presentation/src/frontend/pages/ field": 28,
  "products/presentation/src/frontend/pages/ layout": 133,
  "products/presentation/src/frontend/pages/ style": 4,
};
// (g) Raw <form> elements: path -> count. A form is declared as data and
// rendered by DynamicForm; a server action with no visible field is the one
// kind expected to stay (point 7).
export const rawForms: Debt = {
  "apps/web/app/sign-in/sign-in-view.tsx": 2,
  "products/interview/src/frontend/studio/briefings/behavioural/behavioural-pack.tsx": 1,
  "products/interview/src/frontend/studio/briefings/new-brief.tsx": 1,
  "products/interview/src/frontend/studio/home/interview-card.tsx": 1,
  "products/interview/src/frontend/studio/home/plan-card.tsx": 1,
  "products/interview/src/frontend/studio/live/shared/missing-context-strip.tsx": 1,
  "products/presentation/src/frontend/pages/themes.tsx": 1,
};
