// The toolbar, drawn from the library's Toolbar: the window's controls, the ONE
// capture split button, the microphone split button, the answer style, the model
// chip, the panel toggles (one segmented group), See-through and the shortcut
// list. It holds no session logic: every control calls the one panel session.
// The tables it is drawn from are toolbar-config.ts; what each control says is
// toolbar-model.ts.
//
// [SAFETY] Nothing here conceals capture; See-through only lets the mouse reach
// the page underneath over empty glass, and the window stays visible.
import { Toolbar as LibraryToolbar, Tag } from "@oc-tech/omni-ui-components";
import type { PresentationHost } from "@omnitech/interview-contracts";
import { type ReactNode, useCallback, useEffect, useState } from "react";
import { canPassThrough } from "./hit-regions";
import type { PanelGlass } from "./panel-glass";
import type { PanelSession } from "./panel-views";
import type { Panes } from "./single-panel";
import { CaptureButton, CaptureControl } from "./toolbar-capture";
import { ToolbarLock } from "./toolbar-lock";
import {
  AnswerStyleMenu,
  PaneToggles,
  SeeThroughButton,
  ShortcutsMenu,
} from "./toolbar-menus";
import { MicButton, MicControl } from "./toolbar-mic";
import { WindowDots } from "./window-dots";
import type { PanelWindowMode } from "./window-mode";

export { CaptureButton, MicButton, SeeThroughButton };

type MenuId = "capture" | "mic" | "skill" | "keys";

// What the one window gives the toolbar.
type WindowControls = {
  panes: Panes;
  presentation: PresentationHost;
  glass: PanelGlass;
  windowMode: PanelWindowMode;
  // A menu is open: the window keeps room below the bar for it.
  onMenuOpen(open: boolean): void;
};

export function Toolbar({
  s,
  controls,
  trailing,
}: {
  s: PanelSession;
  controls: WindowControls;
  // After the keyboard button: the start screens' account chip. None while live.
  trailing?: ReactNode;
}) {
  const [menu, setMenu] = useState<MenuId | null>(null);
  const [dotPopup, setDotPopup] = useState(false);
  const onMenuOpen = controls.onMenuOpen;
  const anyOpen = menu !== null || dotPopup;
  useEffect(() => onMenuOpen(anyOpen), [anyOpen, onMenuOpen]);
  // Menus are drawn inside the window's own root, not the document body: the
  // hit regions and the tokens of the panel reach them there.
  const [root, setRoot] = useState<HTMLElement | null>(null);
  const bar = useCallback((node: HTMLDivElement | null) => {
    setRoot(node?.closest<HTMLElement>(".pn-root") ?? null);
  }, []);
  // One menu is open at a time: opening one closes the other.
  const at = (id: MenuId) => ({
    container: root,
    open: menu === id,
    onOpenChange: (open: boolean) =>
      setMenu((now) => (open ? id : now === id ? null : now)),
  });
  const passThrough = canPassThrough(controls.presentation);
  return (
    <div data-drag-handle="" className="pn-contents">
      <LibraryToolbar
        ref={bar}
        label="Session controls"
        variant="floating"
        className="pn-toolbar"
        data-testid="pn-pill"
        leading={
          <WindowDots
            s={s}
            presentation={controls.presentation}
            windowMode={controls.windowMode}
            container={root}
            onPopup={setDotPopup}
          />
        }
        groups={[
          {
            id: "sensors",
            label: "Capture and microphone",
            children: (
              <>
                <CaptureControl s={s} {...at("capture")} />
                <MicControl s={s} {...at("mic")} />
              </>
            ),
          },
          {
            id: "style",
            label: "Answer style",
            children: (
              <>
                <AnswerStyleMenu s={s} {...at("skill")} />
                {s.card?.modelLabel && (
                  <Tag
                    data-testid="pn-model"
                    title={`Generated by ${s.card.modelLabel}`}
                  >
                    {s.card.modelLabel}
                  </Tag>
                )}
              </>
            ),
          },
          {
            id: "panels",
            label: "Panels",
            children: <PaneToggles s={s} panes={controls.panes} />,
          },
          {
            id: "tools",
            label: "Tools",
            children: (
              <>
                <SeeThroughButton
                  glass={controls.glass}
                  passThrough={passThrough}
                />
                <ShortcutsMenu {...at("keys")} />
                {/* The chip is not a session control: it stays live under the lock. */}
                {trailing && (
                  <ToolbarLock.Provider value={null}>
                    {trailing}
                  </ToolbarLock.Provider>
                )}
              </>
            ),
          },
        ]}
      />
    </div>
  );
}
